services:
  - type: web
    name: language-detection-nodejs
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3006
      - key: FASTAPI_URL
        value: https://your-fastapi-app-name.onrender.com 