services:
  - type: web
    name: language-detection-fastapi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
               startCommand: python run_server.py
    envVars:
      - key: PORT
        value: 8000 